name: test
on: push

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard: [1/3, 2/3, 3/3]

    steps:
      - name: Find and split files
        uses: remarkablemark/find-and-split@v1.0.3
        id: tests
        with:
          chunk: ${{ matrix.shard }}
          directory: tests
          pattern: '*Test.php'

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Run tests
        run: ./vendor/bin/phpunit --testdox ${{ steps.tests.outputs.files }}
